name: lint

permissions:
  contents: read

on:
  pull_request:
    paths:
      - "**/*.rs"
      - .github/workflows/lint.yml

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  clippy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: docker://ghcr.io/linkerd/dev:v30-rust
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: ./
      - run: cargo fetch
      - run: rustup component add clippy
      - run: cargo clippy --message-format=json | cargo-action-fmt

  fmt:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: docker://ghcr.io/linkerd/dev:v30-rust
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - run: rustup component add rustfmt
      - run: cargo fmt --check

  docs:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: docker://ghcr.io/linkerd/dev:v30-rust
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: ./
      - run: cargo fetch
      - run: cargo doc --no-deps --message-format=json | cargo-action-fmt
